### ISSUE TITLE
mas can ONLY install paid apps, by doing mas install [identifier]

### ISSUE THREAD

**Issue by mathiasjakobsen** [argon/mas#19] opened 2016-04-11 10:23 UTC
If i try to install LanScan or Pocket (both free apps) i get `ukendt fejl` (unknown error in danish).

**Comment by argon** [comment] 2016-04-14 12:53
Have you already "purchased" the free apps in your account?

**Comment by mathiasjakobsen** [comment] 2016-04-14 17:36
Yep, I have.

**Comment by rlandsberg** [comment] 2016-04-24 02:50
Hey I can confirm the same error, I have a clean El Cap install in a VM with Mas installed from Homebrew. 

 'mas install 867299399' for Omni Focus (paid) works perfectly
'mas install 803453959' for Slack (free but installed on other machines with this AppleID) fails with "Unknown Error"

**Comment by timsutton** [comment] 2016-04-25 00:43
I've found in some cases that I seem to need to set the "Save password" option for free items in the App Store system preferences in order for mas install to work for free items. I'm not sure whether this is related to your issue but thought it's worth mentioning.

**Comment by FLIR31207** [comment] 2016-04-25 11:07
I am seeing the same issue and can confirm that @timsutton's solution works.

**Comment by wischi** [comment] 2016-05-17 15:06
Can the "save password" be automated?

**Comment by timsutton** [comment] 2016-05-17 16:05
It looks to me like that stores unique authentication information, although it's quite possible that it could be done via another (or more) private framework methods..

**Comment by wischi** [comment] 2016-05-18 16:47
I would be happy if mas could invoke the dialog on a freshly setup mac somehow. This didn't work when I tried it. It only worked after I purchased free app I didn't buy before manually.

**Comment by mathiasjakobsen** [comment] 2016-05-23 08:45
I can also confirm, that @timsutton's solution works for me.

**Comment by jamesdh** [comment] 2016-06-16 17:41
I've dug around in `defaults`, doing a pre/post password change diff, and found them to be identical. If anyone has any other ideas on where the password save options might be so that they can be automated, I'd love to hear!

**Comment by argon** [comment] 2016-06-16 17:52
I'm working on this at the moment. It's possible to automate the change but unfortunately the only way so far to change the password setting is by allowing the OS dialog for entering the password. It cannot be totally automatic. I am continuing to investigate in case there is a more low-level solution

—A

**Comment by jamesdh** [comment] 2016-06-16 20:03
@argon I tried the following, but I'm not having luck getting `osascript` on the assistive access list:

```
tell application "System Preferences"
	reveal pane id "com.apple.preferences.appstore"
	activate
end tell

tell application "System Events"
	tell process "System Preferences"
		tell window "App Store"
			set purchases to pop up button 1
			click purchases
			click menu item 2 of menu 1 of purchases
			set free to pop up button 2
			click free
			click menu item 2 of menu 1 of free
		end tell
	end tell
end tell
```

**Comment by edrozenberg** [comment] 2016-07-06 18:36
Don't know if this is related to the same issue, but on this specific app Garmin Basecamp mas hangs and doesn't seem to do anything (app is already installed using App Store app):

````
mas install 411052274
````

**Comment by Luavis** [comment] 2016-07-26 09:41
There are occur errors in call method ```purchase.perform ``` in Downloader.swift
```swift
dispatch_group_enter(group)
purchase.perform { purchase, unused, error, response in
    if let error = error {
        purchaseError = MASError(code: .PurchaseError, sourceError: error)
        dispatch_group_leave(group)
        return
    }
// ...
}
```
I tested with 'Slack' app(fail with Unknown Error.). when print out ```error``` object
```
(lldb) po error
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x600000c0620).
```

**Comment by argon** [comment] 2016-09-15 00:49
I think I have fixed this in the latest code in `master`. If anyone is able to build it and verify the problem is solved for them I will package a new release.

**Comment by timsutton** [comment] 2016-09-15 00:55
I would like to test this, just won't have a chance until tomorrow at the earliest. To be clear, this change (e7750) is what was needed to not trigger the sign in again just for the purposes of storing the password?

**Comment by argon** [comment] 2016-09-15 00:57
I don't fully understand it but with that change I am able to install free apps without being prompted for a password. Without that change I *do* see the password prompt so it appears to have fixed it.

**Comment by timsutton** [comment] 2016-09-15 14:36
Just did a quick test on a VM that had never signed into the App Store. `mas signin <user> <pass>` and `mas install 1018109117` to install El Capitan worked as expected. Only hangup was that my machine was located in Canada, so the App Store had defaulted to that and first prompted me that it would switch it. But that's no different than before.

For what it's worth, I checked the App Store prefs once the download started and this is what it showed:

![screen shot 2016-09-15 at 9 47 22 am](https://cloud.githubusercontent.com/assets/119358/18553870/34d34b8c-7b30-11e6-9a47-9ad6bee74563.png)

**Comment by argon** [comment] 2016-09-15 15:18
The change is not expected to change the password settings, only to fix redownload of previously "purchased" free apps which was not possible before.

**Comment by timsutton** [comment] 2016-09-15 15:31
Thanks for clarifying. I think the settings in my screenshot were the system defaults anyway.

**Comment by argon** [comment] 2016-09-15 15:32
I am closing this issue and will release latest changes as 1.3.0

**Closed by argon** 2016-09-15 15:32 UTC

**Comment by jessepeterson** [comment] 2017-01-10 20:02
I'm not sure if I'm seeing a recurrence of this issue but I'm getting a Mac App Store sign-in dialog when attempting to re-install an app *after a while*. If I do a `mas reset` then `mas signin` it will successfully install an app without a prompt. However sometime later the "state" (I guess) resets itself and I'm no longer able to install free already-purchased apps without entering a password at a MAS dialog.
